# Generated by Django 2.2 on 2020-07-24 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0008_auto_20200707_1824'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0006_contract_auspice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_updated', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('repeat_pauta_day', models.FloatField()),
                ('repeat_in_pauta', models.IntegerField()),
                ('second_total_day', models.IntegerField()),
                ('time_contract', models.IntegerField()),
                ('time_bonification', models.IntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Contract')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Order')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Playlist')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
