# Generated by Django 2.2.7 on 2019-11-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
