# Generated by Django 2.2.7 on 2019-12-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0005_auto_20191204_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='location',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
