# Generated by Django 2.2 on 2019-12-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0008_auto_20191214_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time_operating',
            field=models.TimeField(default='00:00'),
        ),
    ]
