# Generated by Django 2.2 on 2019-12-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0009_product_time_operating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
