# Generated by Django 2.2.7 on 2019-12-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0010_auto_20191216_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name location', max_length=50),
        ),
    ]
