# Generated by Django 2.2.7 on 2020-01-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0011_auto_20191218_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
