# Generated by Django 2.2 on 2020-02-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0013_item_subproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
