# Generated by Django 2.2 on 2020-07-09 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component', '0017_auto_20200708_0417'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_updated', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('sub_product', models.IntegerField(blank=True, null=True)),
                ('electronic', models.IntegerField(blank=True, null=True)),
                ('collaboration', models.CharField(blank=True, max_length=200, null=True)),
                ('work_done', models.TextField(blank=True, max_length=1000, null=True)),
                ('conclusions', models.TextField(blank=True, max_length=1000, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.Product')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
