# Generated by Django 2.2.7 on 2020-03-10 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('component', '0015_auto_20200210_1017'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='play_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_updated', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateField()),
                ('play_list', models.FileField(blank=True, null=True, upload_to='play_list')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.Product')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
