# Generated by Django 2.2 on 2020-04-24 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_contract_auspice'),
        ('content', '0006_playlist_client_detail_time_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist_spot_detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Order'),
            preserve_default=False,
        ),
    ]
