# Generated by Django 2.2 on 2020-07-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_playlist_spot_detail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist_client_detail',
            name='pauta_loop',
            field=models.FloatField(),
        ),
    ]
