# Generated by Django 2.2 on 2020-09-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_drive_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive_urls',
            name='info',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
