# Generated by Django 2.2 on 2020-11-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_drive_urls_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='proyection',
            field=models.BooleanField(default=False),
        ),
    ]
