# Generated by Django 2.2 on 2019-12-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20191212_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pass_contract',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='porcentage_contract',
            field=models.FloatField(default=0),
        ),
    ]
