# Generated by Django 2.2 on 2019-12-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20191214_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='clients'),
        ),
    ]
