# Generated by Django 2.2.7 on 2020-03-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20191216_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='auspice',
            field=models.BooleanField(default=False),
        ),
    ]
