# Generated by Django 2.2 on 2020-09-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_respaldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='respaldo',
            name='year',
            field=models.ImageField(default=2020, upload_to=''),
            preserve_default=False,
        ),
    ]
